### ISSUE TITLE
Unable to register with https

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3511]
It seems there is a client error when trying to register with the controller.

```
$ deis register https://{url}
username: jason.waldrip
password:
password (confirm):
email: jason.waldrip@brandfolder.com
Couldn't connect to the Deis Controller:
[Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
Make sure that the Controller URI is correct and the server is running.
```

**Comment by azurewraith** [comment]
Is the certificate valid?  Can you view a deployed app over https?

**Comment by jwaldrip** [comment]
Yes and yes



—

**Comment by bacongobbler** [comment]
which version of the client is this? I believe this was fixed with #2721.

**Comment by jwaldrip** [comment]
Okay updated to the latest... But now I have a new issue:

```
$ deis apps

 !    WARNING: Client and server API versions do not match. Please consider upgrading.
 !    Client version: 1.2
 !    Server version: 1.1

=== Apps
pg-console
```

**Comment by bacongobbler** [comment]
That's just a warning. It's telling you that your cluster is out of date and some features may not be compatible with the new client. For the most part you can safely ignore as long as you refer to the API reference document to see what's changed in v1.2.

http://docs.deis.io/en/latest/reference/api-v1.2/

**Comment by bacongobbler** [comment]
closing as a duplicate of #2719

**Comment by jwaldrip** [comment]
@bacongobbler my cluster is at v1.5.1 that doesn't explain why I am still seeing the warning. I will open an issue for this.

https://github.com/deis/deis/issues/3528
